### PR TITLE
minor improvements to wording

### PR DESCRIPTION
**Pull request by nlharris**
TBH, I'm not a fan of the space-wasting "you must scroll and scroll to see more content" style, which was super-hip around 2015 but looks a bit dated now. But I realize that changing the style is probably out of scope, so I just made some minor text improvements.

One thing that I addressed is that the features menu points to https://linkml.io/#features, but nothing happens -- it just shows the main page. I think it's meant to bring you back up to the top if you were further down the page -- but since the menu doesn't stay fixed at the top of the page, it's no longer visible to click on if you've scrolled down, so it seems pointless. I therefore am suggesting getting rid of that menu item, but if there's somewhere useful it could point, please lmk where that is!

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Comment by nlharris** [comment]
I don't have permission to merge.

**Comment by nlharris** [comment]
Screen Shot 2022-06-01 at 12 20 36 PM

**Comment by nlharris** [comment]
@sierra-moxon could you merge this so i can see how it looks before i try changing the templates as described in https://github.com/linkml/linkml/issues/759?
thanks!

**Comment by nlharris** [comment]
@sujaypatil96 can you merge this PR? Chris approved it. Thanks!

**Comment by sujaypatil96** [comment]
Merging it in @nlharris.

**Comment by nlharris** [comment]
Thanks Sujay... but uh oh, now https://linkml.io/ shows up empty!! I must have messed something up, maybe missed a close quote or something?

**Comment by sujaypatil96** [comment]
Oh wow, should we revert? Or we can figure out what the issue is, and make another PR immediately.

**Comment by nlharris** [comment]
see PR #4 which i think should fix it

**Pull request merged**
